//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Singluar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Singluar.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კაზინოს ტრანზაქცია დაროლბექდა, თანხის გამოტანა ვერ მოხერხდა.
        /// </summary>
        public static string CasinoRolledBackWithDrawFailed {
            get {
                return ResourceManager.GetString("CasinoRolledBackWithDrawFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქციის id უკვე არსებობს ბაზაში. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string DecreaseBalanceDuplicateTransactionId {
            get {
                return ResourceManager.GetString("DecreaseBalanceDuplicateTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ანგარიშზე თანხა არ არის საკმარისი. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string DecreaseBalanceNotEnoughtBalance {
            get {
                return ResourceManager.GetString("DecreaseBalanceNotEnoughtBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქცია წარმატებულია. ბალანსი დარედაქტირდა..
        /// </summary>
        public static string DecreaseBalanceSuccess {
            get {
                return ResourceManager.GetString("DecreaseBalanceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქცია არ გატარდა. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string DecreaseBalanceTransactionRejected {
            get {
                return ResourceManager.GetString("DecreaseBalanceTransactionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაურკვეველი შეცდომა, უცნობია ბალანსი შეიცვალა თუ არა..
        /// </summary>
        public static string DecreaseBalanceUnknownError {
            get {
                return ResourceManager.GetString("DecreaseBalanceUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კაზინოს ბალანსის შემცირება ვერ მოხერხდა.
        /// </summary>
        public static string DecreasingCasinoBalanceFailed {
            get {
                return ResourceManager.GetString("DecreasingCasinoBalanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თამაშის ბალანსის შემცირება ვერ მოხერხდა.
        /// </summary>
        public static string DecreasingGameBalanceFailed {
            get {
                return ResourceManager.GetString("DecreasingGameBalanceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თანხის შეტანა წარმატებით დასრულდა.
        /// </summary>
        public static string DepositSuccessful {
            get {
                return ResourceManager.GetString("DepositSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თამაის ტრანზაქცია დაროლბექდა, თანხის შეტანა ვერ მოხერხდა.
        /// </summary>
        public static string GameRolledBackDepositFailed {
            get {
                return ResourceManager.GetString("GameRolledBackDepositFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქციის id უკვე არსებობს ბაზაში. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string IncreaseBalanceDuplicateTransactionId {
            get {
                return ResourceManager.GetString("IncreaseBalanceDuplicateTransactionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქცია წარმატებულია. ბალანსი დარედაქტირდა..
        /// </summary>
        public static string IncreaseBalanceSuccess {
            get {
                return ResourceManager.GetString("IncreaseBalanceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტრანზაქცია არ გატარდა. ბალანსი არ შეიცვალა..
        /// </summary>
        public static string IncreaseBalanceTransactionRejected {
            get {
                return ResourceManager.GetString("IncreaseBalanceTransactionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გაურკვეველი შეცდომა, უცნობია ბალანსი შეიცვალა თუ არა..
        /// </summary>
        public static string IncreaseBalanceUnknownError {
            get {
                return ResourceManager.GetString("IncreaseBalanceUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to კაზინოს ტრანზაქციის დაროლბექება ვერ მოხერხდა.
        /// </summary>
        public static string RollingBackCasinoFailed {
            get {
                return ResourceManager.GetString("RollingBackCasinoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თამაშის ტრანზაქციის დაროლბექება ვერ მოხერხდა.
        /// </summary>
        public static string RollingBackGameFailed {
            get {
                return ResourceManager.GetString("RollingBackGameFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თანხა წარმატებით გადმოვიდა კაზინოდან თამაშისკენ.
        /// </summary>
        public static string WithdrawedSuccessfully {
            get {
                return ResourceManager.GetString("WithdrawedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თქვენი მიმდინარე ბალანსებია: თამაში - {0}, კაზინო - {1}.
        /// </summary>
        public static string YourCurrentBalances {
            get {
                return ResourceManager.GetString("YourCurrentBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თქვენი მიმდინარე კაზინოს ბალანსია: {0}.
        /// </summary>
        public static string YourCurrentCasinoBalance {
            get {
                return ResourceManager.GetString("YourCurrentCasinoBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თქვენი მიმდინარე თამაშის ბალანსია: {0}.
        /// </summary>
        public static string YourCurrentGameBalance {
            get {
                return ResourceManager.GetString("YourCurrentGameBalance", resourceCulture);
            }
        }
    }
}
